### PR TITLE
Fix mutual close

### LINKED ISSUE #337: Update merchant watcher to respond to mutual close
Right now, the merchant's mutual close function calls the `verify_contract_closed()` function, which is supposed to wait until the contract is closed on chain. This does not align with the way things are implemented, and in fact, this function is not implemented. 

Instead, the merchant chain watcher should add a condition for this case. The scenario will be: contract is closed and local channel status is `PendingMutualClose`. Then it can call `finalize_mutual_close`.

### PR DESCRIPTION
**Pull request by marsella**
Closes #337 

Before, the merchant's `close()` function called `finalize_mutual_close`. Now, the merchant's watcher calls it.

The most substantial change here is an addition of `MutualCloseBalances` to the merchant database. The merchant watcher cannot tell from the contract itself what the final mutual close balances are, so we need to persist them via the database instead. These changes include
- updating the database schema to include this optional field (`sqlx-data.json` is the generated file)
- updating the database Rust type to include the field
- adding a getter and setter for the field for a specific channel id

Observation: the getters for each field of the database are a bit clumsy -- they're all identical except for the item being queried. Would it be better to have a single getter for the whole row, and have the caller pull out the field relevant to them?

Testing: I think this scenario is not currently caught by the e2e testing infrastructure. Should determine whether it is and either fix it in this PR or make a new issue + PR to address it.

### CODE REVIEW

File: src/bin/merchant/main.rs [hunk 1]
```diff
@@ -277,6 +277,24 @@ async fn dispatch_channel(
         .await?;
     }
 
+    // The channel has not reacted to a customer posting a mutual close transaction on chain
+    // The condition is
+    // - the contract is closed, but
+    // - the channel status is `PendingMutualClose`
+    if contract_state.status()? == ContractStatus::Closed
+        && channel.status == ChannelStatus::PendingMutualClose
```
Comment (gijsvl) [inline src/bin/merchant/main.rs:285]: This seems to leave some options open that shouldn't happen, but nevertheless...
- I believe this code is called when there is an actual change on the contract? Is it possible that a contract changes to ContractStatus::Closed, but ChannelStatus is not PendingMutualClose? Due to an error or a race condition. Did we miss the opportunity to finalize the mutual close or is there a retry?
- Is the other situation possible, PendingMutualClose, but not yet closed on the contract? The idea is that it will still appear, but is there any chance that it doesn't get resolved?

**Review by gijsvl — COMMENTED** [review]
In regard to your comments:
- I think we should take your suggestion and check if this is covered by e2e testing, we can't keep postponing testing to new PRs in my opinion, just because the pile of testing we still have to do just grows, it's not making it easier.
- The separate getters are fine as long as we don't do multiple getters just one after another... Every query takes time, we should make sure we make 1 query at a time and if we can combine queries we should do so. But querying everything at once if it is not necessary might also be unnecessary.

File: src/bin/merchant/main.rs (hunk 1 above)
Comment (marsella) [reply src/bin/merchant/main.rs:291]: Fixed

**Comment by marsella** [comment]
Testing comments remain important, but we've discussed and it seems like they will be better addressed by a significant update to the testing infrastructure, rather than trying to jerry-rig the script we currently have. See #69 for the plan to address this issue.
